Repository vapor/jwt, pull requests merged in 2020-02, with the labels that each got.

#111 Add JWKSCache helper for storing JWKS
  Package.swift
  Sources/JWT/JWKSCache.swift
  Tests/JWTTests/JWTTests.swift
Labels: enhancement

#113 refactor JWKSCache for atomicity
  Sources/JWT/JWKSCache.swift
  Tests/JWTTests/JWTTests.swift
Labels: enhancement

#112 Add JWKSCache helper for storing JWKS
  Package.swift
  Sources/JWT/JWKSCache.swift
  Tests/JWTTests/JWTTests.swift
Labels: enhancement, semver-minor

#114 Adds JWT validation for Apple and Google
  Package.swift
  Sources/JWT/JWKSCache.swift
  Sources/JWT/JWT+Apple.swift
  Sources/JWT/JWT+Google.swift
  Sources/JWT/JWT.swift
  Tests/JWTTests/JWTTests.swift
Labels: enhancement, semver-minor

#115 Beta 3
  Package.swift
Labels: enhancement, semver-major
