Repository vapor/jwt, pull requests merged in 2020-03, with the labels that each got.

#116 Release Candidate 1
  .github/workflows/test.yml
  Package.swift
  README.md
  Sources/JWT/Application+JWT.swift
  Sources/JWT/JWTError+Vapor.swift
  Sources/JWT/Request+JWT.swift
  Tests/JWTTests/JWTTests.swift
Labels: enhancement

#117 Make HMAC signer thread safe
  Sources/JWT/JWTSigner.swift
  Tests/JWTTests/JWTTests.swift
Labels: bug, semver-patch

#118 Updates audience claim check for apple/google
  Sources/JWT/JWT+Apple.swift
  Sources/JWT/JWT+Google.swift
Labels: semver-minor
